### ISSUE TITLE
S3 receive failure

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_05#18]
**Describe the bug**

Received following error:

Premature end of Content-Length delimited message body (expected: 1000; received: 900)

 
**Expected behavior**
A retry in case storage stops streaming.
 
**How to reproduce**
Perhaps oom pth_05 or so.
 
**Screenshots**

 
**Software version**
Pth_07 7.2.4
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by StrongestNumber9** [comment]
Moved to https://github.com/teragrep/pth_06/issues/99
